server:
  port: 3344


spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: http://qtrj.i234.me:30000/nonsense/spring-cloud.git
          search-paths:
            - config-at-gitrepo # 仓库中的哪个目录作为配置目录
          username: felixyin
          password: Ybkk1027
          skip-ssl-validation: true
      label: master
      enabled: true
      allow-override: true
      override-none: true
      discovery:
        enabled: true
        service-id: ${spring.application.name}
    refresh:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    dynamic: true



eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

# 暴露bus刷新配置的端点

management:
  endpoints:
    web:
      exposure:
        #        include: "bus-refresh"
        include: "*"
