version: "3.1"

services:
  rabbit1:
    image: qtrj.i234.me:8084/rabbitmq:3-management
    restart: always
    stdin_open: true
    tty: true
    hostname: rabbit1
    container_name: rabbit1
    ports:
      #        4369 (epmd), 25672 (Erlang distribution)
      - "4369:4369"
      #        5672, 5671 (AMQP 0-9-1 without and with TLS)
      - "5671:5671"
      - "5672:5672"
      #        61613, 61614 (if STOMP is enabled)
      - "61613:61613"
      - "61614:61614"
      #        1883, 8883 (if MQTT is enabled)
      - "1883:1883"
      #        15672 (if management plugin is enabled)
      - "15672:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: "guest"
#      RABBITMQ_DEFAULT_PASS: "guest"
