server:
  port: 8001
spring:
  application:
    #    服务别名
    name: cloud-payment-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.10:3308/learn_springcloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Ybkk1027
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.qtrj.springcloud.entities
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka, http://eureka7002:7002/eureka
    #  instance: # eureka面板status列是否显示ip端详等具体信息，配置了不显示
    # 服务server id
    #    instance-id: payment8001
    # 访问路径可以显示ip地址
#    prefer-ip-address: true