
server:
  port: 81

spring:
  application:
    #    服务别名
    name: cloud-consumer-order
  #     排除spring jdbc
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    zookeeper:
      connect-string: localhost:2181,localhost:2182,localhost,2183
