server:
  port: 8001

spring:
  application:
    #    服务别名
    name: cloud-provider-hystrix-payment

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  instance: # eureka面板status列是否显示ip端详等具体信息，配置了不显示
    instance-id: payment8001 # 服务server id
    prefer-ip-address: true # 访问路径可以显示ip地址
    #    自我保护机制
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
